version: 2
jobs:
  build:
    docker:
      - image: akkyie/thesis
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout

      - run: make build
      - run: make -j2 redpen || true
      - run: .circleci/release.sh
